### PR TITLE
intelligent.foo.ng

### PR DESCRIPTION
**Pull request by myferr**
Subdomain for a documentation website.

### CODE REVIEW

**Comment by Pokymon** [comment]
Do you need to add TXT record for Vercel verification?

**Comment by myferr** [comment]
image
??

**Comment by Pokymon** [comment]
Check your project's domain section in your Vercel dashboard.

**Comment by myferr** [comment]
image

```
Another Vercel account is using this domain. Set the following TXT record on _vercel.foo.ng to use intelligence.foo.ng in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed.

Type: TXT
Name: _vercel
Value: vc-domain-verify=intelligence.foo.ng,4a59cf92fbbc3dd5da6a
```

**Comment by Pokymon** [comment]
Done. You can refresh the page.

**Comment by myferr** [comment]
image
Do I commit a CNAME file with `intelligent.foo.ng` as its contents to my repository?

**Comment by Pokymon** [comment]
You made a typo. It's intelligent, not intelligence.

**Comment by myferr** [comment]
Oh, my bad. It's like 5 am 😭😭

**Comment by myferr** [comment]
image
Another Vercel account is using this domain. Set the following TXT record on _vercel.foo.ng to use intelligent.foo.ng in this project. Once the verification is completed and the domain is successfully configured, the TXT record can be removed.

Type:
* TXT
Name
* _vercel
Value
* vc-domain-verify=intelligent.foo.ng,a3b18374c252799c8427

**Comment by Pokymon** [comment]
Done.

**Pull request merged**
