### PR TITLE
feat: adding new subdomain `zethsu.foo.ng`

### PR DESCRIPTION
**Pull request by zethsue**

### CODE REVIEW

**Comment by Pokymon** [comment]
It looks like you are using Vercel. Could you please provide the TXT record too?

**Comment by zethsue** [comment]
> It looks like you are using Vercel. Could you please provide the TXT record too?

is a must?

**Comment by Pokymon** [comment]
Yes, otherwise it will return as 404. Try adding the domain in the Vercel dashboard and see if it's returning a TXT record verification.

**Comment by zethsue** [comment]
> Yes, otherwise it will return as 404. Try adding the domain in the Vercel dashboard and see if it's returning a TXT record verification.

how to add the TXT record? or i just replace it with the CNAME domain?

this is my records `vc-domain-verify=akio.foo.ng,bf521dcf98242e73415d`
image

btw other subdomain that has been merged its just like vercel CNAME and the subdomain are works but how?

**Comment by zethsue** [comment]
image
how to add it?

but why other is just like using vercel CNAME?

**Comment by Pokymon** [comment]
It must be both CNAME record and TXT record. You can look at the closed issues page. They still need a TXT record for verification.

**Pull request merged**
